---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-watsonx-assistant
    kind: solution
    catalog_id: <to_be_provided>
    offering_id: <to_be_added>
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: <to_be_added>
          region: us-south
